### ISSUE TITLE
ModError: Failed to

### ISSUE THREAD

**Issue by ENDev15** [minetest-mods/mymonths#4]
Recently, I tried to start my Minetest server with the mymonths mod installed, but was immediately given the following error:
```
2016-04-25 20:47:47: ERROR[Main]: ModError: Failed to load and run script from /usr/local/share/minetest/games/minetest_game/mods/mymonths/init.lua:
2016-04-25 20:47:47: ERROR[Main]: ...minetest/games/minetest_game/mods/mymonths/functions.lua:53: attempt to index a nil value
2016-04-25 20:47:47: ERROR[Main]: stack traceback:
2016-04-25 20:47:47: ERROR[Main]: 	...minetest/games/minetest_game/mods/mymonths/functions.lua:53: in main chunk
2016-04-25 20:47:47: ERROR[Main]: 	[C]: in function 'dofile'
2016-04-25 20:47:47: ERROR[Main]: 	...hare/minetest/games/minetest_game/mods/mymonths/init.lua:43: in main chunk
```
What is really weird about this, is the day before mymonths had been working just fine on my server with no errors and full functionality. Now that mymonths gives this error and stops the server from starting, I have a problem. Most of the trees had mymonths custom leaves and there was a lot of snow. So I now have a world full of unknown nodes, including what should be leaves on trees.

### Other Mods:
* areas
* protector
* torches
* wieldview (not working for some reason)
* item_drop
* painting
* bitchange
* computer
* genesis (my mod)
* maptools
* player_textures
* server_tools (another of my mods)
* workbench

Plus all of the default mods of course. I notice that mymonths works fine on my own computer with only default 0.4.13 mods, and no extras. I assume this is a problem between the mods, but I am not sure which one. 

I'm really liking the mymonths mod, so will really appreciate seeing this fixed. Plus, my world is kinda broken...

Thanks!

**Comment by tenplus1** [comment]
I just tested mymonths on my standalone server and couldn't reproduce this error, but... it may be that the 'mymonths_data' file could be corrupt inside your world folder, so maybe deleting that would fix it for you.

**Comment by DonBatman** [comment]
Did you update to the latest version of mymonths or do you use the version meant for minetest 0.4.13?

If you delete the data file like Tenplus1 suggested does it still have the error?

**Comment by ENDev15** [comment]
Thanks @tenplus1, that worked and now everything is running properly. BTW, have you considered using the default snow in one way or another rather than custom mymonths snow? Just curious. I plan to give it a try in the near future though.

**Comment by tenplus1** [comment]
I think Don is using custom snow so that the abm's can remove it quickly from a map area and it wont affect actual snowy biomes in the game.

**Comment by DonBatman** [comment]
What Tenplus1 said plus default snow is used for building and other mods use it so I don't want to break any mods or maps.

**Comment by ENDev15** [comment]
I see what you mean @tenplus1 @DonBatman. I'm going to experiment though and see if I can apply some sort a meta data to all snow that is in the world when the mod is originally loaded so that mymonths will ignore everything with that specific meta tag. Then, whenever snow with the meta attached is removed, the meta data is automatically removed too. 

This still leaves the problem that newly placed snow would be affected by mymonths as it wouldn't contain the meta, but a tool could be added allowing you to set the meta of a block. (Possibly an addition to the screwdriver mod?)

Anyway, I'll give that a go when I get a change. Will probably end up using something from worldedit to check for snow on initial launch.
